build:
	docker-compose -f stack.yml build

deploy:
	docker-compose -f stack.yml up -d

rm:
	docker-compose -f stack.yml down -v

ps:
	docker-compose -f stack.yml ps

push:
	docker-compose -f stack.yml push

pull:
	docker-compose -f stack.yml pull
