version: '3.3'

services:
  web:
    image: gsengun/visium-load-demo-dotnet-wait:2
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    ports:
      - target: 80
        published: 80
